@localhost = https://localhost:5281

POST {{localhost}}/api/orders/items
Accept: application/json
Content-Type: application/json

{
    "itemId": 1,
    "quantity": 1
}

###
POST {{localhost}}/api/orders/items
Accept: application/json
Content-Type: application/json

{
    "itemId": 2,
    "quantity": 1
}

###
POST {{localhost}}/api/orders/items
Accept: application/json
Content-Type: application/json

{
    "itemId": 999,
    "quantity": 1
}

###
GET {{localhost}}/api/orders/current
Accept: application/json
###