global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  # alertmanagers:
  #   - static_configs:
  #       - targets: []
  #     scheme: http
  #     timeout: 10s
  #     api_version: v1

# scrape_configs:
#   - job_name: 'BookStoreMetrics'
#     # basic_auth:
#     #   username: grafana_user
#     #   password: grafana_user
#     honor_timestamps: true
#     scrape_interval: 15s
#     scrape_timeout: 1s
#     metrics_path: /metrics
#     # metrics_path: '/actuator/prometheus'
#     scheme: http
#     follow_redirects: true
#     static_configs:
#       - targets: ['host.docker.internal:8080']
#         labels:
#           product_id: BookStore
#           group: otel-collector
scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']