@localhost = https://localhost:5218

GET {{localhost}}/books-service/books/health
###
GET {{localhost}}/books-service/books/alive
###
GET {{localhost}}/books-service/books
Accept: application/json
###
GET {{localhost}}/books-service/books/1
Accept: application/json
###
GET {{localhost}}/books-service/books/2
Accept: application/json
###
GET {{localhost}}/books-service/books/3
Accept: application/json
###
GET {{localhost}}/users-service/users/1
Accept: application/json
###
POST {{localhost}}/auth-service/login
Accept: application/json
Content-Type: application/json

{
  "email": "john.doe@domain.com",
  "password": "Pa55w0rD!"
}
###

GET {{localhost}}/auth-service/manage/info
Accept: application/json
Authorization: Bearer CfDJ8K13oOXloxJKpWhNlWqNTsTvw9h1nfrjSpaBbWI-VEGUI0AbhWmcInUROZtb9ySeB6JX5sYZ1BzZAOKR66y77r2QbUUcaFv8Eh0mJwv9XoXxwJN7J2jma3vm7hMtrrn3Umx90wUhEzMBHe6YY4t9DWIAiEAAcUAazbTlRdr77f6r6TJYUmkqhU-9x-ZNvlR4CoOPLuH9sKfujEKra_JuT257ErAkP6u8dU2e0-SU0WdfxXQzkKeKlzW1P6NF3TM-WGRv0pJuJU--6YHpjKxyC0yKZ6wm_kcPOnE4PFazhgLGYUUtWF68tLNe17thP2xnLNw8in36qttNS4AYhAReQb1kNuaNjhwF0K9TlljAqxJSwk4CSzLYA3IhHUACJd9KE3YiNU1hqsGlJpaFDsohsC9VozTmIQSTapZxNfJz4gZkEhB9sNjOO9iBvSXLhy1i7LAMS7n5iSdTdM_DA1URSdc9C-ivwSAQoZV4kPIEKXhje7aNMBNCz4laCyD2uNFdq4DsVKRl1C4K0cOcJu0Z0brfN4O6iDidzLk1Vl8PNu03QkoGi90vTfQIYLuvCjV2BvHpWxAUv2o4udaLDyNRxbUWp_xJug5vSecro34MMUTMmlxNID58TxYhMfPSM4x7dZ-dzV3Xou8WApGeX3WgrqL3SJ6x7_kkZVH8T75yw-TaKL1CgtWTyx8GPNWBlvn4_JTckwNQcXN4kgkSiz033zk

###
