@WebApi_HostAddress = http://localhost:5087
@Keycloak_Address = http://localhost:8076

POST {{Keycloak_Address}}/realms/weatherforcast/protocol/openid-connect/token
Content-type: application/x-www-form-urlencoded

grant_type=password&scope=email openid&client_id=weatherforcast-public-client&username=test@test.com&password=root7646

###

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApi_HostAddress}}/weatherforecast-secured/
Accept: application/json
Authorization: Bearer <your_access_token>
