version: '3.9'

networks:
  books_store_network:

services:

  auth-service:
    container_name: books_store_auth_service
    build: 
      context: ../backend
      dockerfile: ./Common/Auth/Dockerfile  
    env_file:
      - ../backend/Common/Auth/.devops/test.env  
    volumes:
      - ./docker_volumes/postgres:/app/out
    ports:
      - 8080:8080 # http
    depends_on:
      - db
    networks:
        - books_store_network

  books-api:
    container_name: books_store_books_api
    build: 
      context: ../backend
      dockerfile: ./microservices/src/Books/Dockerfile  
    env_file:
      - ../backend/microservices/src/Books/.devops/test.env  
    volumes:
      - ./docker_volumes/postgres:/app/out
    ports:
      - 8090:8080 # http
    depends_on:
      - db
    networks:
        - books_store_network