version: '3.9'

networks:
  books_store_network:

services:

  api-gateway:
    container_name: books_store_api_gateway
    build: 
      context: ../backend
      dockerfile: ./Common/ApiGateway/Dockerfile  
    env_file:
      - ../backend/Common/ApiGateway/.devops/test.env  
    volumes:
      - ./docker_volumes/api-gateway:/app
    ports:
      - 8080:8080 # http
    depends_on:
      - db
      - auth-service
      - books-api
    networks:
        - books_store_network

  auth-service:
    container_name: books_store_auth_service
    build: 
      context: ../backend
      dockerfile: ./Common/Auth/Dockerfile  
    env_file:
      - ../backend/Common/Auth/.devops/test.env  
    volumes:
      - ./docker_volumes/auth-service:/app
    ports:
      - 9010:8080 # http
    depends_on:
      - db
    networks:
        - books_store_network

  books-api:
    container_name: books_store_books_api
    build: 
      context: ../backend
      dockerfile: ./microservices/src/Books/Dockerfile  
    env_file:
      - ../backend/microservices/src/Books/.devops/test.env  
    volumes:
      - ./docker_volumes/books-api:/app
    ports:
      - 9020:8080 # http
    depends_on:
      - db
    networks:
        - books_store_network