version: '3.9'

networks:
  books_store_postgres_network:

services:

  db:
    container_name: books_store_db
    image: postgres:latest
    ports:
      - 5433:5432
    volumes:
      - ./config/postgres:/docker-entrypoint-initdb.d      
      - ./docker_volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=books,books_user; orders,orders_user; identity,users_user; subscriptions,subscriptions_user
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - books_store_postgres_network