version: '3.9'

services:

  db:
    container: books_store_db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./docker_volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=books_store