version: '3.9'

networks:
  books_store_rabbitmq_network:

services:

  rabbitmq:
    # https://hub.docker.com/_/rabbitmq
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./docker_volumes/rabbitmq/data/:/var/lib/rabbitmq/
        - ./docker_volumes/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - books_store_rabbitmq_network