version: '3.3'

services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.25
    container_name: otel-demo-jaeger-ui
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686 # ui
      - 14250:14250
      # - 14268:14268

  otel-collector:
    image: otel/opentelemetry-collector:0.47.0
    container_name: otel-demo-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-config.yml:/etc/otel-collector-config.yml:ro
    ports:
      - 4317:4317
