@localhost = http://localhost:5219

POST {{localhost}}/register
Accept: */*
Content-Type: application/json

{
  "email": "john.doe@domain.com",
  "password": "Pa55w0rD!"
}

###

POST {{localhost}}/login?useCookies=true&useSessionCookies=true
Accept: application/json
Content-Type: application/json

{
  "email": "john.doe@domain.com",
  "password": "Pa55w0rD!"
}

###

POST {{localhost}}/refresh
Accept: application/json
Content-Type: application/json

{
  "refreshToken": "{refreshToken}"
}

###

GET {{localhost}}/confirmEmail?userId=5f1076aa-371c-404b-9dac-be0281196d39&code={code}&changedEmail={changedEmail}
Accept: */*
Cookie: .AspNetCore.Identity.Application=CfDJ8K13oOXloxJKpWhNlWqNTsTKOf-t9oPlieB49PlR9wcPv54oh-eS6JRw3cdIwCluE-pJAcZJ4045VUdbqpb_rjPPAcYdoCTxRJzPKEDwQmZ7W6jzjFytsBbyyJFW2ZiQYUBN8b_BWAqyXFzGrJK9by4RS1DI80_YcLw3GJ_E0gxC6yKcJVZn2qrNQ9_gN79-eZwSi3c_PlIL2XsOfuAM2t2w1c4A1nlmrM1TVg-mAhnSsP_sjsxftKKRNPE2GyYKSdySe7r7yRY4l1vPkJvTorCAA3SFT2GBsj3FYTHA0Mu2C8Y3eR5Dg4gIkon6JoQORY8yX-GOVRjP_1kC_Ftn8guz6EknqwvAjdXwlFr1nB-XEQ2zIHS5UFF6UH6bPSg-09Uxugg-GSo7q4yWTUNQ5C-_XdiRtdYOVX2DmLOyK-WATfU466FfPaHbFIheyXl2Yk0RCwgynatL_K7QH2ugK8M2YQ9Yew_wLgbkYF-qxej4dSvo1s-zUBbMTpqFdad-0CD3Y6JdBJdG2xqAEJAdjK-jaloASFK2J3rifb_5L3YQ8YFen84x9PR4SgqUDJxF8PCWLnBJiEuQ1b-YU8ZX3_m31wiebolzm0sLTjSTnp24DDN2OgI3H4m5ygRFINj81vxgcmZEOGc_lqcWIWAPf2_XQ4yBLAIGxNvitUep-Oj1rDy9Z-XAesibHNo5ee_tsnO7s13IBMM-7TLURhHlXTiDgT2fbApkdQVwvFuWM5Anq7EpTCYqAgtozsTsGUvykA; path=/; secure; samesite=lax; httponly

###

POST {{localhost}}/resendConfirmationEmail
Accept: */*
Content-Type: application/json

{
  "email": "john.doe@domain.com"
}

###

POST {{localhost}}/forgotPassword
Accept: */*
Content-Type: application/json

{
  "email": "john.doe@domain.com"
}

###

POST {{localhost}}/resetPassword
Accept: */*
Content-Type: application/json

{
  "email": "john.doe@domain.com",
  "resetCode": "string",
  "newPassword": "NewPa55w0rD!"
}

###

POST {{localhost}}/manage/2fa
Accept: application/json
Content-Type: application/json

{
  "enable": true,
  "twoFactorCode": "AbCdE",
  "resetSharedKey": true,
  "resetRecoveryCodes": true,
  "forgetMachine": true
}

###

GET {{localhost}}/manage/info
Accept: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8K13oOXloxJKpWhNlWqNTsTE-v-hupV1u_lTsiXREldIKPbW25Jy_S2ASM1Df2fwHeLcuZ-lHFnVcQA23AecxmKg_tb36MywqJgfr4xiJ3qJByeYXGvbyxLLpCoR1AyYpGAq5HfYdwUOrxnc4DonUo2J3NOk0K-LQey8kY8cOzaWIqwahdpzmxosrtIvKpQ2C-fEjf2u9Nblme24JVVksS-vZTPdHn5iNjJWkz7tgbUuCFFFhsHWopvz2qLObLGtnbpbeByxDcbOVi8HWNo17lwjrRgjQcmSswfGMwG6lpA5nvbL5m3JLmK2KK3CPxBxntTDutaNGTd7Y0dE_zjmLxaU6JxpODvhRoWtxbU2mhHdnhIRAWwOdySoMTXtnGJx9IfRywy0OPF4o5I56ZsCaK8h6-wEgQI9qXT_Z5zK4eb3mNgu6gAwsQr_Nz312SFQb4Ucy2tl1fVXFiqapo0px3uVuPgo8DFBDknY41QlNc5KStrV7xvEUo2I5zG0N4hQjteiHwOI-ggQbjJgEHFIjw7FVul8BlHee0tdovgtGDypN65bqH-StvHGSIlmsGsFk9XZIFuIZklNarOGII26_sC33oltS1jTQOAES0mLH-GnuJYANxl69xlLei8_cL7GlH2tSdkhdSEMFapViExoQ7iGZiDgVrUl-QFPGf9Dzo3dOgvW4dBypzrEDuADXHIo32v1-k-W5CjPObU7kpC9EOqgiIb8bfrjyDTlK6mzzk70ECURZZCV2IJnkOca8M_1Fg; path=/; secure; samesite=lax; httponly

###

POST {{localhost}}/manage/info
Accept: application/json
Content-Type: application/json

{
  "newEmail": "string",
  "newPassword": "string",
  "oldPassword": "string"
}

###

POST {{localhost}}/logout
Accept: application/json
Content-Type: application/json

{}

###
