apiVersion: 1

datasources:
- name: Loki
  type: loki
  access: proxy 
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  apiVersion: 1
  # jsonData:
  #   - datasourceUid: otlp
  #     matcherRegex: (?:"traceid"):"(\w+)"
  #     name: TraceID
  #     url: $${__value.raw}
- name: Prometheus
  type: prometheus
  url: http://prometheus:8080
  isDefault: false
  access: proxy
  editable: true
  basicAuth: false
  version: 1
  jsonData:
    tlsSkipVerify: true
