# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "dotnet test"

on:
  workflow_dispatch:
    inputs:
      dotnetAppPath:
        description: "Folder of the .NET app"
        type: string
        required: true

run-name: .NET Run Tests - ${{ github.ref }} - ${{ inputs.dotnetAppPath }}

jobs:
  Run-Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Test
        run: dotnet test --logger "trx;LogFileName=test-results.trx"
        working-directory: ${{ inputs.dotnetAppPath }}

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults/test-results.trx
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
