# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 'dotnet test'

on:
  workflow_dispatch:
    inputs:
      dotnetAppPath:
        description: 'Folder of the .NET app'
        type: string
        required: true

jobs:
  Run-Tests:

    runs-on: ubuntu-latest

    run-name: .NET Run Tests - ${{ inputs.dotnetAppPath }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Test
      run: dotnet test
      working-directory: ${{ inputs.dotnetAppPath }}
